services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER:-template}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-template}
      POSTGRES_DB: ${DATABASE_NAME:-template}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    networks:
      - template_project_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: "ng9"
    networks:
      - template_project_network

volumes:
  db_data:

networks:
  template_project_network:
